src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/utilities/translations.ts

PP9-8503: SDK translations

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/components/basket/basket.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/components/content-browser/content-browser.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/configuration.ts

PP9-8544: action buttons bug

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/components/schema-browser-item/schema-browser-item.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/components/schema-browser-item/schema-browser-item.component.theme.scss
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/components/schema-browser-item/schema-browser-item.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/schema-browser.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/schema-browser.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/theming/_theming.scss

- Schema browser:
- implemented single click to select item and double click to open
- removed duplicated css from the schema browser item scss theme file
- _theming.scss:
- added missing import for schema browser item theme file

PP9-10074 - Implemented single and double click events in the schema browser

---

src/picturepark-sdk-v1-angular/package-lock.json
src/picturepark-sdk-v1-angular/package.json
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-oidc/package.json
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/package.json
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/browser-item-base/browser-item-base.component.scss
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/package.json
src/picturepark-sdk-v1-fetch/package.json
src/picturepark-sdk-v1-pickers/package.json

Update css for list view
Increased package version

PP9-10355 - Typescript SDK: Content Browser List view thumbnails missing

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/api-services.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/services.extensions.ts
src/picturepark-sdk-v1-angular/projects/share-viewer/src/app/share-detail/share-detail.component.ts

- Services extensions: swapped tap function call by mergeMap
- Share detail component: refactored due to deprecation on forkJoin function call

PP9-10420 - Shares: date in DP for contents in shared links looks as fluid code

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/components/content-browser-item/content-browser-item.component.html

- Content browser item: fixed Basket Tooltip for list view

PP9-10494 - Typescript SDK: Content Picker List view incorrect tooltip on remove from basket icon

---

src/picturepark-sdk-v1-angular/.github/workflows/gpr-publish.yml

- added a YAML file to publish packages on the Github Package Repository on pushes to the master branch

PP9-10342 - Typescript SDK: Automatic npm package creation

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/components/share-content-dialog-item/share-content-dialog-item.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/content-item-thumbnail/content-item-thumbnail.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/content-item-thumbnail/content-item-thumbnail.component.scss
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/content-item-thumbnail/content-item-thumbnail.component.ts

Noticed some problems in the issue when testing in QA01

Add shadow to share dialog

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/layer-panels/components/layer-fields/layer-fields.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/layer-panels/layer-panels.module.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/layer-panels/models/layer-field.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/layer-panels/services/layer-field.service.ts

- Fixed translation for layer fields

PP9-10489 - Content Portal: Implement language switch

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/services/localization/localization.service.ts
src/picturepark-sdk-v1-angular/projects/share-viewer/src/app/app.component.ts

- fixed localize function
- fixed format error on share viewer app component

PP9-10722 - Typescript SDK: Localization service uses the first system language

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/components/schema-browser-item/schema-browser-item.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/components/schema-browser-item/schema-browser-item.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/schema-browser.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/schema-browser.component.ts

- click events detected in the Schema Browser Item component and emitted
- emitted event handled in the Schema Browser component

PP9-10274 - Excel Roundtripping app: List items single click event

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/components/content-browser-item/content-browser-item.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/content-browser.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/browser-base/browser-base.component.scss
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/browser-item-base/browser-item-base.component.scss

- Content browser list view uses the whole width of the screen to display the content in mobile mode

PP9-10924 - Content Portal: Mobile: Weird Layout on top buttons

---

src/picturepark-sdk-v1-angular/package-lock.json
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/browser-toolbar/browser-toolbar.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/content-browser.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/schema-browser/schema-browser.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-browser/share-browser.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/browser-base/browser-base.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/services/api-services.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/services/services.extensions.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/tests/share-service.spec.ts
src/picturepark-sdk-v1-angular/projects/share-viewer/src/app/share-detail/share-detail.component.ts
src/picturepark-sdk-v1-angular/src/app/content-picker/embed.service.ts
src/picturepark-sdk-v1-angular/src/app/share-manager/components/share-manager-item/share-manager-item.component.ts
src/picturepark-sdk-v1-fetch/src/index.ts
swagger/PictureparkSwagger.json

API:
- API updated
- Fetch index and picturepark-sdk-v1-angular api-services updated with nswag
- picturepark-sdk-v1-angular services.extensions updated according to api-services changes
Share service get method calls updated with the required extra parameter
Content Browser component static sorting types replaced with dynamic sort types from the channel

Angular SDK: ContentBrowser - Show sort fields defined in channel and enable user to sort by them

---

src/picturepark-sdk-v1-angular/src/app/app-routing.module.ts
src/picturepark-sdk-v1-angular/src/app/components/application-menu/application-menu.component.ts
src/picturepark-sdk-v1-angular/src/app/home/home.component.html
src/picturepark-sdk-v1-angular/src/app/list-item-picker/components/list-items-picker/list-items-picker.component.ts

- Change route from list-item-picker to list-item-browser

PP9-11313 - ListItem Picker: Can select items, but not choose selection

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/components/content-image-preview/content-image-preview.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/components/content-image-preview/content-image-preview.component.scss
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/components/content-image-preview/content-image-preview.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/facade/download.facade.ts

- Content image preview component: Specific class for icons
- CreateDownloadLink waitForCompletion with timeout

PP9-11307 - Content Portal: Details viewer: items displayed too small or exceed screen on mobile

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.component.ts

- internalRecipients were not being taken into account

PP9-11336 - Content Portal: Close Share Dialog when Share is created successfully

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/facade/search.facade.ts

- added resetRequestState method

PP9-11371 - ContentPortal: Items not loaded when switching from dashboard to items back and forth

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/components/content-image-preview/content-image-preview.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-details-dialog/fullscreen.service.ts

- When previewing an icon use the preview image with the preview URL switch case

PP9-11375 - Content Portal: Cannot view xml files

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/aggregation-list/aggregation-list.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/aggregation-list/aggregation-list.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/facade/search.facade.ts

- Search facade synced with UI Migration project
- Aggregation list component synced with UI Migration project, imports reorganised,

PP9-12054 - Aggregation filters disabled still show bug fix

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/language-switch/language-switch.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/services/language.service.ts

- the language is only saved to storage when the user manually selects it using the language switch dropdown

PP9-12370 - Angular SDK: Share details > Open details with share language

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/aggregation-list/aggregation-list.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/locale.module.ts

- Fixed issue when filtering aggregation filters when no filters were available

PP9-12370 - Fixed issue with share details text not being translated to share language

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/search-suggest-box/search-suggest-box.component.ts

- Reverted setSearchString previous changes

PP9-12588 - Content Picker - Search suggestions - filter with all options is shown instead of suggestion

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/basket/basket.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/content-browser/content-browser.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.component.html
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.component.scss
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.module.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/dialog-base/dialog-base.component.scss
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/styles/global_styles.scss

- Changed mobile layout
- Synced Basket and Content Browser share dialog dimensions

PP9-12703 - Content Portal: Mobile: Share button disappears when more than 8 items are selected

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular/src/lib/facade/search.facade.ts

- reverted changes on Search facade done as part of commit 2c62c009e33a8259677eeae4e74ee3a549821811

PP9-12761 - Content Portal: Cannot browse items

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.component.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/components/dialog-base/dialog-base.component.ts

- Access Original toggle set to true by default if enabled
- Fixed linting errors

PP9-13048 - Content Picker. No message for the user that he has permission limits for sharing content

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.component.ts
src/picturepark-sdk-v1-angular/projects/share-viewer/src/app/share-detail/share-detail.component.scss

- Expiration date field was not being passed to the create share method

PP9-13125 - Content picker -> Share Content. Share isn't shown as expired in the share browser

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/list-browser/list-browser.module.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/features-module/share-content-dialog/share-content-dialog.component.ts

PP9-13048 - Clear notifications when pressing Share button again

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/directives/user-interaction.directive.ts
src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-ui/src/lib/shared-module/shared-module.module.ts

- do not show context menu on mobile

PP9-13336 - Mobile - Android. Detail is opened on scrolling browser.

---

src/picturepark-sdk-v1-angular/projects/picturepark-sdk-v1-angular-oidc/src/lib/oidc-auth.service.ts
src/picturepark-sdk-v1-angular/src/app/app.component.ts

- If query params are specified and they contain the postUrl, pass the postUrl param to the requireLogin function

PP9-13673 - Typescript SDK: Content Picker: PostUrl parameter get lost during login process

---

src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular-ui/src/lib/features-module/browser-toolbar/browser-toolbar.component.html
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular-ui/src/lib/features-module/browser-toolbar/browser-toolbar.component.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular-ui/src/lib/features-module/channel-picker/channel-picker.component.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular-ui/src/lib/features-module/content-browser/content-browser.component.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular-ui/src/lib/features-module/list-browser/list-browser.component.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular-ui/src/lib/features-module/schema-browser/schema-browser.component.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular-ui/src/lib/features-module/share-browser/share-browser.component.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular-ui/src/lib/shared-module/components/browser-base/browser-base.component.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular/src/lib/facade/search.facade.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular/src/lib/utilities/helper.ts
src/picturepark-sdk-v2-angular/projects/picturepark-sdk-v2-angular/src/lib/utilities/storage-key.enum.ts

Rollback changes to preserve in local storage

PP9-16157 revert all changes
